Improve version metadata handling
Previous names were confusing. Now, in the colophon file there are two
version metadata symbols: VERSION and BUILD, instead of RELEASE.

The BUILD is the canonical build identifier for the project, containing
both the public and private version segments, with information from the
repository current status.

The VERSION is the canonical version for the project, and contains only
the tag and the post-release marker.

For releases, both symbols contain the release number.

Code and git hooks have been adapted.

diff --git a/tools/hooks/common b/tools/hooks/common
--- a/tools/hooks/common
+++ b/tools/hooks/common
@@ -1,18 +1,12 @@
 #!/bin/sh
-
 die() {
-    echo "$1";
-    exit 1;
+    echo "[$?] $1."
+    exit 1
 }
 
 update_colophon() {
-    COLOPHON_PATH=$(python tools/colophon.py) || die 'The colophon file could not be generated.'
-    COLOPHON_PATH=${COLOPHON_PATH//\\//}
-    COLOPHON_PATH=${COLOPHON_PATH#"$REPO_ROOT"/}
-    VERSION=$(grep '^VERSION' "$COLOPHON_PATH" | cut -d"'" -f2)
-    RELEASE=$(grep '^RELEASE' "$COLOPHON_PATH" | cut -d"'" -f2)
+    COLOPHON_PATH=$(python tools/colophon.py) || die 'The colophon file could not be generated'
 }
-
 
 if [ -z "$VIRTUAL_ENV" ]; then
     if [ -f .venv/Scripts/activate ]; then
